name: agents-platform
description: Agent Operating System - Infrastructure as Code
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: gcp-typescript
